import 'primeicons/primeicons.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';
import 'primereact/resources/primereact.css';
import 'primeflex/primeflex.css';

import React from 'react';
import { FilterMatchMode, FilterOperator } from 'primereact/api';
import { DataTable } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { TableData } from './base';
import VerifiedIcon from '@mui/icons-material/Verified';

import mockDataJson from '../../../database/communities.json';

import { isMobile } from 'react-device-detect';

class CommunitiesTableData extends TableData {
  initFilterValues: { [key: string]: {} } = {
    global: { value: null, matchMode: FilterMatchMode.CONTAINS },
    name: {
      operator: FilterOperator.AND,
      constraints: [{ value: null, matchMode: FilterMatchMode.STARTS_WITH }]
    },
    type: {
      operator: FilterOperator.AND,
      constraints: [{ value: null, matchMode: FilterMatchMode.STARTS_WITH }]
    },
    market: {
      operator: FilterOperator.AND,
      constraints: [{ value: null, matchMode: FilterMatchMode.STARTS_WITH }]
    },
    tags: {
      operator: FilterOperator.AND,
      constraints: [{ value: null, matchMode: FilterMatchMode.CONTAINS }]
    },
    foundation_year: {
      operator: FilterOperator.AND,
      constraints: [{ value: null, matchMode: FilterMatchMode.CONTAINS }]
    }
  };

  constructor() {
    super('communities', mockDataJson);
  }

  create(): JSX.Element {
    const nameBodyTemplate = (rowData) => {
      const link = '/communities/' + rowData.autogenerated.filename.replace('.json', '');
      if (rowData.autogenerated.partnership) {
        return (
          <React.Fragment>
            <VerifiedIcon fontSize="small" color="primary" /> <a href={link}>{rowData.name} </a>
          </React.Fragment>
        );
      }
      return (
        <React.Fragment>
          <a href={link}>{rowData.name}</a>
        </React.Fragment>
      );
    };
    const eventsTypeBodyTemplate = (rowData) => {
      if (rowData.events_type != undefined) {
        return rowData.events_type.join(', ');
      }
      console.log('Error display: ' + rowData);
    };

    const tagsBodyTemplate = (rowData) => {
      if (rowData.tags != undefined) {
        return rowData.tags.join(', ');
      }
      console.log('Error display: ' + rowData);
    };

    const header = this.renderHeader();

    return (
      <DataTable
        value={this.customers}
        paginator
        className="p-datatable-customers"
        rows={20}
        dataKey="id"
        filters={this.filters}
        filterDisplay="menu"
        loading={this.loading}
        responsiveLayout="scroll"
        globalFilterFields={['name', 'platform']}
        header={header}
        emptyMessage="No communities found."
        footer={this.renderFooterCopy('community', '/contributors/communities')}
      >
        <Column
          alignHeader="center"
          field="name"
          header="Name"
          body={nameBodyTemplate}
          filter
          filterPlaceholder="Search by name"
        />
        <Column
          alignHeader="center"
          field="type"
          header="Type"
          filter
          filterPlaceholder="Search by type"
        />
        <Column
          alignHeader="center"
          hidden={isMobile ? true : false}
          field="platform"
          header="Platform"
          filter
          filterPlaceholder="Search by platform"
        />
        <Column
          alignHeader="center"
          hidden={isMobile ? true : false}
          field="events_type"
          header="Events Type"
          body={eventsTypeBodyTemplate}
          filter
          filterPlaceholder="Search by events type"
        />
        <Column
          alignHeader="center"
          hidden={isMobile ? true : false}
          field="tags"
          header="Tags"
          filter
          filterPlaceholder="Search by tags"
          body={tagsBodyTemplate}
        />
        <Column
          alignHeader="center"
          hidden={isMobile ? true : false}
          field="description"
          header="Description"
        />
      </DataTable>
    );
  }
}

export default function Table(): JSX.Element {
  return new CommunitiesTableData().create();
}
