import React from 'react';
import Grid from '@mui/material/Grid2';
import { Link, Typography } from '@mui/material';
import Chip from '@mui/material/Chip';
import LinkIcon from '@mui/icons-material/Link';
import Button from '@mui/material/Button';
import Breadcrumbs from '@mui/material/Breadcrumbs';
import VerifiedIcon from '@mui/icons-material/Verified';
import ArrowRightIcon from '@mui/icons-material/ArrowRight';
import { getTags } from '@site/src/components/Pages';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
interface CommunityPageProps {
    data: {
        name: string;
        url: string;
        type: string;
        platform: string;
        description: string;
        tags: Array<string>;
        events_type: Array<string>;
        autogenerated: any;
    };
}

export default function ContentPage(props: CommunityPageProps) {
    return (
        <Grid container>
            <Breadcrumbs aria-label="breadcrumb">
                <Link underline="hover" color="inherit" href="/">
                    Home
                </Link>
                <Link color="inherit" href="/communities">
                    Communities
                </Link>
                <Typography>{props.data.name}</Typography>
            </Breadcrumbs>

            <Grid size={{ xs: 12 }}>
                <Typography variant="h2" component="h1">
                    {props.data.name}{' '}
                    {props.data.autogenerated.partnership ? (
                        <VerifiedIcon className="primary" />
                    ) : null}
                </Typography>
                <Typography component="h2" marginBottom={2}>
                    {props.data.description}
                </Typography>

                <Link
                    href={props.data.url}
                    className="primary"
                    target="_blank"
                    paddingRight={1}
                >
                    <Chip
                        label="Website"
                        style={{ background: '#1976d2', color: '#FFFFFF' }}
                        icon={<LinkIcon style={{ color: '#FFFFFF' }} />}
                    />
                </Link>

                <Typography
                    component="h3"
                    variant="h5"
                    marginTop={3}
                    marginBottom={1}
                >
                    Community
                </Typography>
                <Grid>
                    <Grid size={{ xs: 12 }}>
                        <Button className="primary">
                            Main format <ChevronRightIcon /> {props.data.type}
                        </Button>
                    </Grid>

                    <Grid size={{ xs: 12 }}>
                        <Button className="primary">
                            Main platform <ChevronRightIcon />{' '}
                            {props.data.platform}
                        </Button>
                    </Grid>

                    <Typography
                        component="h3"
                        variant="h5"
                        marginTop={3}
                        marginBottom={1}
                    >
                        Type of events
                    </Typography>
                    {props.data.events_type.map((key) => (
                        <Grid size={{ xs: 12 }}>
                            <Button className="primary">
                                <ArrowRightIcon /> {key}
                            </Button>
                        </Grid>
                    ))}
                </Grid>
                {getTags(props.data.tags)}
            </Grid>
        </Grid>
    );
}
