import React from 'react';
import Grid from '@mui/material/Grid2';
import { Link, Typography } from '@mui/material';
import Chip from '@mui/material/Chip';
import LinkIcon from '@mui/icons-material/Link';
import Button from '@mui/material/Button';
import Breadcrumbs from '@mui/material/Breadcrumbs';
import VerifiedIcon from '@mui/icons-material/Verified';
import ArrowRightIcon from '@mui/icons-material/ArrowRight';
import { getTags } from '@site/src/components/Pages';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import PublicIcon from '@mui/icons-material/Public';
interface DigitalNomadPageProps {
    data: {
        name: string;
        state_name: string;
        required_documents: Array<string>;
        internet_roaming: string;
        daily_average_cost: number;
        description: string;
        tags: Array<string>;
        how_to_arrive: Array<string>;
        how_to_move: Array<string>;
        resources: Array<string>;
        coworking: Array<string>;
        autogenerated: any;
    };
}

export default function DigitalNomadPageProps(props: DigitalNomadPageProps) {
    return (
        <Grid container>
            <Breadcrumbs aria-label="breadcrumb">
                <Link underline="hover" color="inherit" href="/">
                    Home
                </Link>
                <Link color="inherit" href="/digital-nomads">
                    Digital Nomads
                </Link>
                <Typography>{props.data.name}</Typography>
            </Breadcrumbs>
            <Grid size={{ xs: 12 }}>
                <Typography variant="h2" component="h1">
                    {props.data.name}{' '}
                </Typography>

                <Typography component="h2" marginBottom={2}>
                    {props.data.description}
                </Typography>

                <Chip
                    label={props.data.state_name}
                    style={{ background: '#1976d2', color: '#FFFFFF' }}
                    icon={<PublicIcon style={{ color: '#FFFFFF' }} />}
                />

                <Typography
                    component="h3"
                    variant="h5"
                    marginTop={3}
                    marginBottom={1}
                >
                    Details
                </Typography>
                <Grid size={{ xs: 12 }}>
                    <Button className="primary">
                        Roaming <ChevronRightIcon />{' '}
                        {props.data.internet_roaming}
                    </Button>
                </Grid>

                <Grid size={{ xs: 12 }}>
                    <Button className="primary">
                        Daily cost <ChevronRightIcon />{' '}
                        {props.data.daily_average_cost} €
                    </Button>
                </Grid>
                <Grid size={{ xs: 12 }}>
                    <Button className="primary">
                        Allowed Documents <ChevronRightIcon />{' '}
                        {props.data.required_documents.map(
                            (key, index) =>
                                key +
                                (props.data.required_documents.length ==
                                index + 1
                                    ? ''
                                    : ', '),
                        )}
                    </Button>
                </Grid>

                <Typography
                    component="h3"
                    variant="h5"
                    marginTop={3}
                    marginBottom={1}
                >
                    Resources
                </Typography>
                <Grid container>
                    {props.data.resources.map((key, index) => (
                        <Grid size={{ xs: 6, sm: 3 }}>
                            <Button
                                className="primary"
                                href={key}
                                target="_blank"
                            >
                                <LinkIcon /> Resource #{index + 1}
                            </Button>
                        </Grid>
                    ))}
                </Grid>
                <Typography
                    component="h3"
                    variant="h5"
                    marginTop={3}
                    marginBottom={1}
                >
                    Coworking
                </Typography>
                <Grid container>
                    {props.data.coworking.map((key, index) => (
                        <Grid size={{ xs: 6, sm: 3 }}>
                            <Button
                                className="primary"
                                href={key}
                                target="_blank"
                            >
                                <LinkIcon /> Coworking #{index + 1}
                            </Button>
                        </Grid>
                    ))}
                </Grid>

                <Typography
                    component="h3"
                    variant="h5"
                    marginTop={3}
                    marginBottom={1}
                >
                    How to arrive
                </Typography>
                <Grid container>
                    {props.data.how_to_arrive.map((key) => (
                        <Grid size={{ xs: 6, sm: 3 }}>
                            <Button className="primary">
                                <ArrowRightIcon /> {key}
                            </Button>
                        </Grid>
                    ))}
                </Grid>

                <Typography
                    component="h3"
                    variant="h5"
                    marginTop={3}
                    marginBottom={1}
                >
                    How to move
                </Typography>
                <Grid container>
                    {props.data.how_to_move.map((key) => (
                        <Grid size={{ xs: 6, sm: 3 }}>
                            <Button className="primary">
                                <ArrowRightIcon /> {key}
                            </Button>
                        </Grid>
                    ))}
                </Grid>

                {getTags(props.data.tags)}
            </Grid>
        </Grid>
    );
}
