import React from 'react';
import Grid from '@mui/material/Grid2';
import { Link, Typography } from '@mui/material';
import Breadcrumbs from '@mui/material/Breadcrumbs';
import { getTags } from '@site/src/components/Pages';

interface StartupPageProps {
    data: {
        name: string;
        site_url: string;
        type: string;
        market: string;
        description: string;
        tags: Array<string>;
        foundation_year: number;
        autogenerated: any;
    };
}

export default function StartupPageProps(props: StartupPageProps) {
    return (
        <Grid container>
            <Breadcrumbs aria-label="breadcrumb">
                <Link underline="hover" color="inherit" href="/">
                    Home
                </Link>
                <Link color="inherit" href="/startups">
                    Startups
                </Link>
                <Typography>{props.data.name}</Typography>
            </Breadcrumbs>
            <Grid size={{ xs: 12 }}>
                <Typography variant="h2" component="h1">
                    {props.data.name}{' '}
                </Typography>

                <Typography component="h2" marginBottom={2}>
                    {props.data.description}
                </Typography>

                {getTags(props.data.tags)}
            </Grid>
        </Grid>
    );
}
