#!/bin/bash
# filepath: /Users/fabrizio.cafolla/projects/fabrizio/italiaopensource.com/website/scripts/create_landings.sh

# Base directory setup
BASEDIR=$(dirname "$(dirname "$(realpath "$0")")")

# Function to create page header
create_page_header() {
  local name="$1"
  local tags="$2"
  local description="${name} landing page in italiaopensource.com."
  
  echo "---"
  echo "title: ${name}"
  echo "description: ${description}"
  echo "tags: ${tags}"
  echo "---"
  echo ""
  echo "# ${name}"
  echo ""
}

# Process startups data
create_startups_landing() {
  local output_file="$BASEDIR/src/pages/landings/startups.md"
  echo "Creating startups landing page..."
  
  create_page_header "Startups Landing" "tech startups, open-source, opensource" > "$output_file"
  
  jq -c '.data[]' "$BASEDIR/database/startups.json" | while read -r item; do
    name=$(echo "$item" | jq -r '.name')
    filename=$(echo "$item" | jq -r '.autogenerated.filename' | sed 's/\.json//')
    echo "Creating $name in startups landing"
    
    market=$(echo "$item" | jq -r '.market')
    type=$(echo "$item" | jq -r '.type')
    description=$(echo "$item" | jq -r '.description')
    foundation_year=$(echo "$item" | jq -r '.foundation_year // "N/A"')
    tags=$(echo "$item" | jq -r '.tags | map("`" + . + "`") | join(" | ")')
    
    {
      echo -e "### [$name](/startups/$filename)\n"
      echo -e "**Market**: $market ($type)\n"
      [ "$foundation_year" != "N/A" ] && echo -e "**Created in**: $foundation_year\n"
      [ "$description" != "null" ] && echo -e "**Description**: $description\n"
      echo -e "${tags}\n"
      echo -e "---\n"
    } >> "$output_file"
  done
}

# Process opensource data
create_opensource_landing() {
  local output_file="$BASEDIR/src/pages/landings/opensources.md"
  echo "Creating opensource projects landing page..."
  
  create_page_header "Opensource Projects Landing" "opensource projects, open-source, opensource" > "$output_file"
  
  jq -c '.data[]' "$BASEDIR/database/opensource.json" | while read -r item; do
    name=$(echo "$item" | jq -r '.name')
    filename=$(echo "$item" | jq -r '.autogenerated.filename' | sed 's/\.json//')
    echo "Creating $name in opensources landing"
    
    type=$(echo "$item" | jq -r '.type')
    description=$(echo "$item" | jq -r '.description')
    tags=$(echo "$item" | jq -r '.tags | map("`" + . + "`") | join(" | ")')
    updated_at=$(echo "$item" | jq -r '.autogenerated.analytics.updated_at // ""')
    {
      echo -e "### [$name](/opensources/$filename)\n"
      echo -e "**Type**: $type\n"
      [ "$description" != "null" ] && echo -e "**Description**: $description\n"
      [ -n "$updated_at" ] && echo -e "**Last updated**: $updated_at\n"
      echo -e "${tags}\n"
      echo -e "---\n"
    } >> "$output_file"
  done
}

# Process communities data
create_communities_landing() {
  local output_file="$BASEDIR/src/pages/landings/communities.md"
  echo "Creating communities landing page..."
  
  create_page_header "Communities Landing" "tech community, open-source, opensource" > "$output_file"
  
  jq -c '.data[]' "$BASEDIR/database/communities.json" | while read -r item; do
    name=$(echo "$item" | jq -r '.name')
    filename=$(echo "$item" | jq -r '.autogenerated.filename' | sed 's/\.json//')
    echo "Creating $name in communities landing"
    
    events_type=$(echo "$item" | jq -r '.events_type | join(", ")')
    description=$(echo "$item" | jq -r '.description')
    tags=$(echo "$item" | jq -r '.tags | map("`" + . + "`") | join(" | ")')
    
    {
      echo -e "### [$name](/communities/$filename)\n"
      echo -e "**Event Type**: $events_type\n"
      [ "$description" != "null" ] && echo -e "**Description**: $description\n"
      echo -e "${tags}\n"
      echo -e "---\n"
    } >> "$output_file"
  done
}

# Process digital nomads data
create_digital_nomads_landing() {
  local output_file="$BASEDIR/src/pages/landings/digital-nomads.md"
  echo "Creating digital nomads landing page..."
  
  create_page_header "Digital Nomads Landing" "digital nomads, remote working, open-source, opensource" > "$output_file"
  
  jq -c '.data[]' "$BASEDIR/database/digital-nomads.json" | while read -r item; do
    name=$(echo "$item" | jq -r '.name')
    filename=$(echo "$item" | jq -r '.autogenerated.filename' | sed 's/\.json//')
    echo "Creating $name in digital nomads landing"
    
    state_name=$(echo "$item" | jq -r '.state_name')
    internet_roaming=$(echo "$item" | jq -r '.internet_roaming')
    description=$(echo "$item" | jq -r '.description')
    tags=$(echo "$item" | jq -r '.tags | map("`" + . + "`") | join(" | ")')
    
    {
      echo -e "### [$name](/digital-nomads/$filename)\n"
      echo -e "**State**: $state_name\n"
      echo -e "**Internet Roaming**: $internet_roaming\n"
      [ "$description" != "null" ] && echo -e "**Description**: $description\n"
      echo -e "${tags}\n"
      echo -e "---\n"
    } >> "$output_file"
  done
}

# Main execution
mkdir -p "$BASEDIR/src/pages/landings"
create_startups_landing
create_opensource_landing
create_communities_landing
create_digital_nomads_landing

echo "All landing pages have been created successfully!"
exit 0
