name: "Terraform plan"
description: "Runs a composite step action"

inputs:
  WORKSPACE:
    description: "The workspace to deploy the infrastructure"
    required: true
  AWS_DEFAULT_REGION:
    description: "The AWS region to deploy the infrastructure"
    required: true
  AWS_ACCOUNT_ID:
    description: "The AWS account ID to deploy the infrastructure"
    required: true
  AWS_ROLE_NAME:
    description: "OIDC Role name"
    required: true
  AWS_TERRAFORM_STATE_BUCKET:
    description: "Terraform state bucket name"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/${{ inputs.AWS_ROLE_NAME }}
        aws-region: ${{ inputs.AWS_DEFAULT_REGION }}
        role-session-name: github-actions

    - name: Set Terraform 1.7
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9"

    - name: Terraform Plan
      shell: bash
      working-directory: infrastructure
      env:
        WORKSPACE: ${{ inputs.WORKSPACE }}
        AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
        AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
        AWS_TERRAFORM_STATE_BUCKET: ${{ inputs.AWS_TERRAFORM_STATE_BUCKET }}
      run: |
        devbox shell
        devbox run infra setup
