import { resolveInternalUrl } from "@walle/utils";

/**
 * The catalog sections of italiaopensource.com. Each maps a public route segment to an
 * Astro content collection (defined in src/content.config.ts, synced from
 * awesome-italia-opensource) plus the copy used to present it. Adding a section is a
 * single entry here — the dynamic `[section]` pages pick it up automatically.
 */
export type SectionKey = "opensource" | "communities";
export type CollectionName = "opensource" | "community";

export interface SectionConfig {
  key: SectionKey;
  collection: CollectionName;
  label: string;
  singular: string;
  description: string;
}

export const SECTIONS: Record<SectionKey, SectionConfig> = {
  opensource: {
    key: "opensource",
    collection: "opensource",
    label: "Open Source",
    singular: "Project",
    description: "Our awesome list of open-source projects created by Italian companies and developers.",
  },
  communities: {
    key: "communities",
    collection: "community",
    label: "Communities",
    singular: "Community",
    description: "Our awesome list of tech communities in Italy.",
  },
};

export const SECTION_LIST: SectionConfig[] = Object.values(SECTIONS);

type Entry = { id: string; data: Record<string, unknown> };

/** The short label shown as a card/detail badge, per section. */
export function badgeOf(key: SectionKey, data: Record<string, any>): string | undefined {
  switch (key) {
    case "opensource":
      return data.autogenerated?.analytics?.language || data.type || undefined;
    case "communities":
      return data.platform || data.type || undefined;
  }
}

/** Map a collection entry to CatalogCard props (title, description, badge, meta row). */
export function catalogCardOf(key: SectionKey, entry: Entry) {
  const data = entry.data as Record<string, any>;
  const badge = badgeOf(key, data);
  const metas: { icon?: string; text: string }[] = [];
  if (key === "opensource") {
    const a = data.autogenerated?.analytics ?? {};
    if (a.stargazers_count != null) metas.push({ icon: "fa:star", text: String(a.stargazers_count) });
    if (a.forks_count != null) metas.push({ icon: "fa:code-fork", text: String(a.forks_count) });
    if (data.license) metas.push({ icon: "fa:balance-scale", text: String(data.license) });
  } else {
    if (data.type) metas.push({ icon: "fa:tag", text: String(data.type) });
    const events = (data.events_type ?? []).filter(Boolean).length;
    if (events) metas.push({ icon: "fa:calendar", text: `${events} event type${events > 1 ? "s" : ""}` });
  }
  return {
    title: String(data.name ?? entry.id),
    href: resolveInternalUrl(`/${key}/${entry.id}`),
    description: String(data.description ?? ""),
    ...(badge ? { badge: { text: badge, variant: "primary" as const } } : {}),
    metas,
  };
}

/** The primary external link for a detail page, per section. */
export function primaryLinkOf(key: SectionKey, data: Record<string, any>) {
  switch (key) {
    case "opensource":
      return { href: data.repository_url, label: "View repository" };
    case "communities":
      return { href: data.url, label: "Open community" };
  }
}

export interface Facet {
  key: string;
  label: string;
  options: string[];
}

const uniqSorted = (vals: (string | undefined | null)[]): string[] =>
  [...new Set(vals.map((v) => (v ?? "").trim()).filter(Boolean))].sort((a, b) =>
    a.localeCompare(b)
  );

/**
 * Filter facets for a section's list — the "filterable by everything" dropdowns.
 * Facet `key` must be a plain word (used as `data-<key>` on each item; walle's
 * CollectionFilters matches option value against the item's comma-split `data-<key>`).
 */
export function facetsOf(key: SectionKey, entries: Entry[]): Facet[] {
  const rows = entries.map((e) => e.data as Record<string, any>);
  if (key === "opensource") {
    return [
      { key: "type", label: "Type", options: uniqSorted(rows.map((d) => d.type)) },
      {
        key: "language",
        label: "Language",
        options: uniqSorted(rows.map((d) => d.autogenerated?.analytics?.language)),
      },
      { key: "license", label: "License", options: uniqSorted(rows.map((d) => d.license)) },
    ];
  }
  return [
    { key: "type", label: "Type", options: uniqSorted(rows.map((d) => d.type)) },
    { key: "platform", label: "Platform", options: uniqSorted(rows.map((d) => d.platform)) },
    {
      key: "events",
      label: "Events",
      options: uniqSorted(rows.flatMap((d) => d.events_type ?? [])),
    },
  ];
}

/** The `data-*` filter attributes for one item, matching facetsOf's keys. */
export function filterAttrsOf(key: SectionKey, data: Record<string, any>): Record<string, string> {
  const search = [data.name, data.description, ...(data.tags ?? [])]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
  if (key === "opensource") {
    return {
      "data-type": data.type ?? "",
      "data-language": data.autogenerated?.analytics?.language ?? "",
      "data-license": data.license ?? "",
      "data-search": search,
    };
  }
  return {
    "data-type": data.type ?? "",
    "data-platform": data.platform ?? "",
    "data-events": (data.events_type ?? []).join(","),
    "data-search": search,
  };
}
