/**
 * Vite's built-in asset handling forces base64 inlining for any import with this query
 * suffix, regardless of file size: Astro's own `astro/client.d.ts` declares `*.woff` (the
 * default URL-import form) but not this query variant. Used by `og/fonts.ts` to embed the
 * bundled fallback font's bytes directly into its own JS chunk: a plain `import.meta.url`
 * relative path breaks once that code is bundled into a different output location.
 */
declare module "*.woff?inline" {
  const dataUri: string;
  export default dataUri;
}

/**
 * Virtual modules generated by `defineWalleConfig` (src/@walle/define-config.ts).
 * Declared here so consumers get types without depending on how they are produced.
 */
declare module "virtual:walle-pwa" {
  const pwa: {
    enabled: boolean;
    manifestHref?: string;
    registerHref?: string;
    themeColor?: string | null;
    appleTouchIcon?: string | null;
  };
  export default pwa;
}

/**
 * Commerce UI gated at the module-graph level: `null` when `commerce.mode !== "shop"`,
 * so a site with commerce off never emits a chunk for the cart components.
 */
declare module "virtual:walle-features" {
  export const CartMount: typeof import("./commerce/CartMount.astro").default | null;
  export const CartBadge: typeof import("./commerce/CartBadge.astro").default | null;
}

/**
 * One entry per configured `typography.fonts`: what Head.astro needs to render one
 * `<Font cssVariable preload />` per font: everything else (name, provider, weights...) is
 * only relevant to Astro's own build-time `fonts` config, resolved in define-config.ts.
 */
declare module "virtual:walle-fonts" {
  export const fonts: Array<{ cssVariable: string; preload: boolean }>;
}

/** Palette and `typography.fonts` from theme.json, resolved at config time for OG rendering. */
declare module "virtual:walle-theme-data" {
  const data: {
    palette: Record<string, string>;
    fonts: Array<{
      name: string;
      provider: "local" | "google" | "fontsource";
      src?: string[];
      weights?: (string | number)[];
    }>;
  };
  export default data;
}

/**
 * One export per embeddable component, each typed against its own "standard" walle
 * implementation. A site override must accept the same props and slots to be a valid
 * replacement, so this is the contract a `components.<key>` path is held to.
 */
declare module "virtual:walle-components" {
  export const navbar: typeof import("./components/features/Navbar/Navbar.astro").default;
  export const footer: typeof import("./components/features/Footer.astro").default;
  export const card: typeof import("./components/features/Card/BasicCard.astro").default;
  export const breadcrumbs: typeof import("./components/features/Breadcrumbs.astro").default;
  export const pageHeader: typeof import("./components/features/Sections/HeaderStandard.astro").default;
  export const toc: typeof import("./components/features/Blog/BlogTableOfContents.astro").default;
}
