import { existsSync } from "node:fs";
import { basename } from "node:path";
import { file, glob } from "astro/loaders";
import { defineCollection, z } from "astro:content";

/**
 * Awesome data collections.
 *
 * Data is synced from https://github.com/italia-opensource/awesome-italia-opensource
 * (its `analytics/*.json` aggregates) into `src/content/data/` by `scripts/sync-database.sh`.
 * Each aggregate is `{ "data": [ ... ], "metadata": { ... } }`; the parser below lifts the
 * `data` array and derives a stable `id` from each item's `autogenerated.filename`, so every
 * item becomes an addressable content entry (index + detail page) with no per-item file.
 */
const awesomeParser = (text: string) => {
  const parsed = JSON.parse(text);
  const items = Array.isArray(parsed) ? parsed : (parsed.data ?? []);
  return items.map((item: Record<string, unknown>) => {
    const filename = (item.autogenerated as { filename?: string } | undefined)?.filename ?? "";
    const id = basename(String(filename), ".json") || String(item.name ?? "").toLowerCase();
    return { id, ...item };
  });
};

// The awesome data uses `null` for missing optional strings (e.g. ~20% of projects have a
// null description). Coerce any non-string to "" so a missing value renders as empty, not a
// schema error.
const softStr = z.preprocess((v) => (typeof v === "string" ? v : ""), z.string());

// GitHub metadata appended by the awesome repo's pipeline. Kept permissive on purpose:
// it is data we display opportunistically, and its exact shape is owned upstream.
const autogenerated = z.object({}).passthrough().optional();

const opensource = defineCollection({
  loader: file("src/content/data/opensource.json", { parser: awesomeParser }),
  schema: z.object({
    name: z.string(),
    description: softStr,
    type: softStr,
    tags: z.array(z.string()).default([]),
    site_url: softStr.optional(),
    repository_platform: softStr,
    repository_url: z.string(),
    license: softStr,
    autogenerated,
  }),
});

const community = defineCollection({
  loader: file("src/content/data/communities.json", { parser: awesomeParser }),
  schema: z.object({
    name: z.string(),
    description: softStr,
    type: softStr,
    platform: softStr,
    url: z.string(),
    tags: z.array(z.string()).default([]),
    events_type: z.array(z.string()).default([]),
    autogenerated,
  }),
});

// Curated markdown pages (annual reports, editorial content). Authored in-repo, not synced.
const posts = defineCollection({
  loader: glob({ base: "./src/content/posts", pattern: "**/*.{md,mdx}" }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    slug: z.string().optional(),
    tags: z.array(z.string().max(24)).min(1).max(10).optional(),
    publishDate: z.date().optional(),
    readingTime: z.string().optional(),
    author: z.string().optional(),
    image: z.string().optional(),
    draft: z.boolean().optional(),
  }),
});

// Managed @walle BaseLayout calls getCollection("wiki") on every page. This consumer ships no
// wiki, so the loader is guarded to an empty collection (walle starter pattern) — present so the
// call resolves, empty so no /wiki UI is built.
const hasWiki = existsSync("../../wiki");
const wiki = defineCollection({
  loader: glob({
    base: hasWiki ? "../../wiki" : "./src",
    pattern: hasWiki ? "*.md" : "__no_wiki__/*.md",
  }),
});

export const collections = { opensource, community, posts, wiki };
