name: Build Website

on:
  repository_dispatch:
    types:
      - build-website
      - build-website-command
  workflow_dispatch:
    inputs:
      hash-commit-awesome-italia-opensource:
        description: "Set the commit hash from awesome-italia-opensource"
        required: false
        default: ""

# Permissions for terramform-init action
permissions:
  id-token: write
  contents: read

env:
  WORKSPACE: "production"

jobs:
  build-website:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Load env
        id: env
        run: |
          build_pr_branch_name="feat/build-website-${{ github.event_name }}-${{ github.sha }}"
          checkout_commit_sha="${{ github.sha }}"

          if [ "${{ inputs.hash-commit-awesome-italia-opensource }}" != "" ] ; then
            build_pr_branch_name="feat/build-website-awesome-${{ inputs.hash-commit-awesome-italia-opensource }}"
          fi

          if [ "${{ github.event.client_payload.slash_command.args.named.pr_sha }}" != "" ]; then
            checkout_commit_sha="${{ github.event.client_payload.slash_command.args.named.pr_sha }}"
          fi

          echo "checkout_commit_sha=${checkout_commit_sha}" >> $GITHUB_OUTPUT
          echo "checkout_commit_sha=${checkout_commit_sha}"

          echo "build_pr_branch_name=${build_pr_branch_name}" >> $GITHUB_OUTPUT
          echo "build_pr_branch_name=${build_pr_branch_name}"

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.env.outputs.checkout_commit_sha }}
          fetch-depth: 0

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "website/.nvmrc"
          cache-dependency-path: website/yarn.lock
          cache: "yarn"

      - name: Terraform Init
        id: terraform
        uses: ./.github/workflows/actions/terraform-init
        timeout-minutes: 5
        with:
          WORKSPACE: ${{ env.WORKSPACE }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
          AWS_TERRAFORM_STATE_BUCKET: ${{ secrets.AWS_TERRAFORM_STATE_BUCKET }}

      - name: Build
        id: build
        timeout-minutes: 5
        run: |
          make download

          git checkout HEAD -- infrastructure/.terraform.lock.hcl # Ignore changes to the lock file
          status=$(git status -s)
          echo "## Status"
          echo "${status}"

          # Skip build if only metadata.json has changed and the pipeline was triggered by awesome-italia-opensource
          if [[ "${{ inputs.hash-commit-awesome-italia-opensource }}" != "" ]] && [[ "${status}" == " M website/database/metadata.json" ]] ; then
            echo "has_changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          make setup-website VIRTUAL_ENV=false
          make build

          echo "has_changed=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: ${{ steps.build.outputs.has_changed == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ACTION_WORKFLOWS }}
          branch: ${{ steps.env.outputs.build_pr_branch_name }}
          title: "feat(website): update awesome data"
          body: "Update awesome data from: ${{ github.event_name }}"
          commit-message: "Update awesome data from: ${{ github.event_name }}"
          author: "FabrizioCafolla <${{ secrets.ACTION_EMAIL }}>"
          add-paths: |
            website/src/*
            website/database/*

      - name: Update comment
        if: ${{ success() && github.event.client_payload.slash_command.args.named.comment_id }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.ACTION_WORKFLOWS }}
          comment-id: ${{ github.event.client_payload.slash_command.args.named.comment_id }}
          reactions: hooray

      - name: Failure
        if: ${{ failure() && github.event.client_payload.slash_command.args.named.comment_id }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.ACTION_WORKFLOWS }}
          comment-id: ${{ github.event.client_payload.slash_command.args.named.comment_id }}
          body: |
            :warning: Deployment failed. See #[${{ github.run_number }}](https://github.com/italia-opensource/italiaopensource.com/actions/runs/${{ github.run_id }}) for more details.
