name: Deploy Infrastructure

on:
  repository_dispatch:
    types:
      - deploy-infrastructure
  workflow_dispatch:

# Permissions for terramform-init action
permissions:
  id-token: write
  contents: read

env:
  AWS_TERRAFORM_STATE_BUCKET: ${{ secrets.AWS_TERRAFORM_STATE_BUCKET }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
  WORKSPACE: ${{ secrets.WORKSPACE }}

jobs:
  plan-infrastructure:
    name: Plan
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: github-actions

      - name: Set Terraform 1.9
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9"

      - name: Infrastructure plan
        working-directory: infrastructure
        timeout-minutes: 5
        env:
          VENV_DIR: .venv
        run: |
          make setup
          make check-drift

  apply-infrastructure:
    name: Apply
    runs-on: ubuntu-22.04
    environment:
      name: production
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: github-actions

      - name: Set Terraform 1.9
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9"

      - name: Infrastructure apply
        working-directory: infrastructure
        timeout-minutes: 10
        run: |
          make setup
          make apply-auto-approve
