name: Deploy Website

permissions:
  id-token: write
  contents: read

on:
  repository_dispatch:
    types:
      - deploy-website
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-website:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: github-actions

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          cache: "pip"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "website/.nvmrc"
          cache-dependency-path: website/yarn.lock
          cache: "yarn"

      - name: Build
        working-directory: website
        timeout-minutes: 5
        run: |
          yarn setup
          yarn build

      - name: Deploy
        working-directory: website
        timeout-minutes: 5
        env:
          BUCKET_NAME: italiaopensource.com-website-${{ secrets.AWS_ACCOUNT_ID }}-${{ secrets.WORKSPACE }}
        run: |
          yarn deploy ${BUCKET_NAME}
