name: Deploy Website

permissions: read-all

on:
  repository_dispatch:
    types:
      - deploy-website
      - deploy-website-command
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-website:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Load ENV
        run: |
          if [ "${{ github.event.client_payload.slash_command.args.named.pr_sha }}" == "" ]; then
            echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          else
            echo "COMMIT_SHA=${{ github.event.client_payload.slash_command.args.named.pr_sha }}" >> $GITHUB_ENV
          fi

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: "true"

      - name: Build
        timeout-minutes: 5
        run: |
          devbox run website build

      - name: Deploy
        timeout-minutes: 5
        run: |
          devbox run deploy

      - name: Update comment
        if: ${{ success() && github.event.client_payload.slash_command.args.named.comment_id }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.ACTION_WORKFLOWS }}
          comment-id: ${{ github.event.client_payload.slash_command.args.named.comment_id }}
          reactions: hooray

      - name: Failure
        if: ${{ failure() && github.event.client_payload.slash_command.args.named.comment_id }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.ACTION_WORKFLOWS }}
          comment-id: ${{ github.event.client_payload.slash_command.args.named.comment_id }}
          body: |
            :warning: Deployment failed. See #[${{ github.run_number }}](https://github.com/italia-opensource/italiaopensource.com/actions/runs/${{ github.run_id }}) for more details.
